decoration { # DONE
# See https://wiki.hyprland.org/Configuring/Variables/ for more

# > window corners
        rounding       = 4   # 5
        rounding_power = 5 # 2.0
# opacity and dimming
        active_opacity     = 1.0 # 1.0
        inactive_opacity   = 1.0 # 1.0
        fullscreen_opacity = 1.0 # 1.0

        dim_modal    = true # true
        dim_inactive = false # false
        dim_strength = 0.15  # 0.5
        dim_special  = 0.0  # 0.2
        dim_around = 0.0

# screen_shader = [[Empty]]
        border_part_of_window = true # true

        blur { # TO BE REFINED
                # backgroun blur
                enabled = true # true

                size   = 4 # 8
                passes = 3 # 1

                ignore_opacity    = true  # true
                new_optimizations = true  # true
                xray              = true # false

                # color correction
                noise      = 0.0       # 0.0117
                contrast   = 1.0        # 0.8916
                brightness = 1.0        # 0.8172
                vibrancy   = 0.0        # 0.1696
                vibrancy_darkness = 0.0 # 0.0

                special = true # false

                popups = true
                popups_ignorealpha = 0.05 # 0.2
                input_methods = false
                input_methods_ignorealpha = 0.05
        }

        shadow { # DONE
# drop shadow
                enabled = true        # true
                range         = 6     # 4
                render_power  = 4     # 3
                sharp         = false # false
                ignore_window = true  # true

                color          = $rosewater # rgba(1a1a1aee)
                color_inactive = $crust     # unset

                offset = 0, 0
                scale  = 1.0
        }

        # glow { # APPARENTLY DNE???
        #         enabled = true
        #         range = 4
        #
        # }
}
