input {
# kb_model
        kb_layout = us
        kb_variant = altgr-intl
# stuff, see wiki

        repeat_rate = 25 # 25
        repeat_delay = 300 # 600

        sensitivity = 0.0 # -1.0 - 1.0, 0 means no modification.
        accel_profile = adaptive # [[Empty]]
        force_no_accel = false # false, keep it at false
        left_handed = false # false
# scroll_points
        scroll_method = 2fg # [[Empty]]
# scroll_button = 0 # 0
# scrloo_button_lock
# scroll_factor
# natural_scroll

        follow_mouse = 2 # 1
	
    touchpad {
         natural_scroll = true
         disable_while_typing = true
         tap-to-click = true
    }

    # kb_options = caps:swapescape
}
