scrolling {
        fullscreen_on_one_column = true
        column_width = 0.49
        explicit_column_widths = 0.2, 0.3, 0.49, 0.5, 0.7, 0.98
        focus_fit_method = 1 #1: bring into view, 0: center
        follow_focus = true
        follow_min_visible = 1
        direction = right
}
