source = $HOME/.config/hypr/src/themes/mocha.conf
source = $HOME/.config/hypr/src/active-wallpaper.conf

$font = FiraCode Nerd Font Propo:font_features=cv11,cv14

# GENERAL
general {
        hide_cursor = true
        ignore_empty_input = true
        immediate_render = false
        text_trim = true
        fail_timeout = 2000
}

# AUTHENTICATIOIN
auth {
        pam:enabled = true
        fingeriprint:enabled = false
}

# ANIMATIONS
animations {

}

# BACKGROUND
background {
        monitor = eDP-1
        path = $wallpaperdir/$wallpaper
        blur_passes = 2
        blur_radius = 10
        # color = $base
}

# LAYOUT
# label {
#   monitor =
#   text = Layout: $LAYOUT
#   color = $text
#   font_size = 25
#   font_family = $font
#   position = 30, -30
#   halign = left
#   valign = top
# }

shape {
        monitor =
        size = 1920, 150
        color = rgba($mantleAlpha55)
        halign = center
        valign = top
        position = 0,0
}
shape {
        monitor =
        size = 1920, 150
        color = rgba($baseAlpha55)
        halign = center
        valign = bottom
        position = 0,0
}

shape { # CIRCLE
        monitor = 
        size = 200, 200
        color = rgba($baseAlpha55)
        rounding = -1
        border_size = 3
        border_color = $accent
        halign = center
        valign = center
        position = 0, 0
        zindex = 0
}

# TIME
label {
        monitor =
        text = $TIME
        color = $text
        font_size = 30
        font_family = $font
        position = 0, 5
        halign = center
        valign = center
}

# DATE
label {
        monitor =
        text = cmd[update:10000] date +"%a %d"
        color = $text
        font_size = 15
        font_family = $font
        halign = center
        valign = center
        position = 0, -22
}

# NAME
label {
        monitor =
        text = $USER
        color = $text
        font_size = 15
        font_family = $font
        halign = center
        valign = center
        position = 0, 35
}

# INPUT FIELD
input-field {
        monitor =
        size = 150, 50
        outline_thickness = 0
        dots_size = 0.2
        dots_spacing = 0.25
        dots_center = true
        outer_color = $accent
        inner_color = rgba(00,00,00,00)
        font_color = $text
        fade_on_empty = true
        placeholder_text = <span foreground="##$textAlpha"><i>...</i></span>
        hide_input = false
        check_color = $accent
        fail_color = $red
        fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
        capslock_color = $yellow
        position = 0, -47
        halign = center
        valign = center
}

# FINGERPRINT
# {
#         monitor = "";
#         text = "$FPRINTPROMPT";
#         color = "$text";
#         font_size = 14;
#         font_family = $font;
#         position = "0, -107";
#         halign = "center";
#         valign = "center";
# }

# USER AVATAR
# image {
#         monitor =
#         path = $HOME/.face
#         size = 100
#         border_color = $accent
#         position = 0, 75
#         halign = center
#         valign = center
# }

