# ~/.config/hypr/hyprapaper.conf 

source = $HOME/.config/hypr/wallpaper.conf

splash = false

wallpaper {
        monitor = eDP-1
        path = $wallpaperdir/$wallpaper
        fit_mode = cover
}

wallpaper {
        monitor = HDMI-A-1
        path = $wallpaperdir/$wallpaper
        fit_mode = cover
}
