# ~/.config/hypr/active-wallpaper.conf 

# $wallpaper = catppuccin-mocha-eva1.jpg
# $wallpaper = catppuccin-mocha-asuka.2.png
# $wallpaper = catppuccin-mocha-asuka.3.jpg
# $wallpaper = catppuccin-mocha-eva-stylized.png
# $wallpaper = catppuccin-mocha-asuka-water.jpg
# $wallpaper = catppuccin-mocha-asuka-nrsfw.jpg
# $wallpaper = catppuccin-mocha-black-hole.png
# $wallpaper = catppuccin-mocha-asuka-nrsfw-1.png
# $wallpaper = generic-M51.png
# $wallpaper = catppuccin-mocha-M51.png
# $wallpaper = catppuccin-mocha-dark-waves.jpg

# ASTROPHOTOGRAPHY
# $wallpaper = catppuccin-mocha-orion.jpg
$wallpaper = generic-arch-galaxy.jpg
# $wallpaper = catppuccin-mocha-arch-galaxy.jpg
# $wallpaper =







$wallpaperdir = ~/.config/walls
