gestures {
    # see https://wiki.hypr.land/Configuring/Gestures
    workspace_swipe_distance = 300 # 300
    workspace_swipe_invert = true  # true
}

gesture = 3, vertical, workspace
gesture = 3, right, dispatcher, layoutmsg, focus l
gesture = 3, left, dispatcher, layoutmsg, focus r
